#!/bin/bash -l
#SBATCH -p chimp
#SBATCH -n 1
#SBATCH -t 5-00:00:00
#SBATCH -J vcftools-fst
#SBATCH -o slurm-%N-%u-%A.out
#SBATCH -e slurm-%N-%u-%A.err


echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

echo "working directory = "$SLURM_SUBMIT_DIR

echo "Launch job"

DIR_inputdata=/mnt/NEOGENE3/share/dna/hsa/genotypes/1000G_20130502
DIR_software=/usr/local/sw/vcftools-0.1.16/bin
DIR_output=/mnt/NEOGENE1/toTransfer/workshopfiles/PBS

$DIR_software/vcftools --gzvcf $DIR_inputdata/ALL.chr2.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz --min-alleles 2 --max-alleles 2 --remove-indels --weir-fst-pop eas.txt --weir-fst-pop eurasia.txt --fst-window-size 10000 --fst-window-step 5000 --out $DIR_output/eas_euas_norep.chr2

$DIR_software/vcftools --gzvcf $DIR_inputdata/ALL.chr2.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz --min-alleles 2 --max-alleles 2 --remove-indels --weir-fst-pop africa.txt --weir-fst-pop eurasia.txt --fst-window-size 10000 --fst-window-step 5000  --out $DIR_output/af_euas_norep.chr2.2

$DIR_software/vcftools --gzvcf $DIR_inputdata/ALL.chr2.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz --min-alleles 2 --max-alleles 2 --remove-indels --weir-fst-pop africa.txt --weir-fst-pop eas.txt --fst-window-size 10000 --fst-window-step 5000 --out $DIR_output/af_eas_norep.chr2.2




echo "All Done!"


